### ISSUE TITLE
chocolatey packages not approved?

### ISSUE THREAD

**Issue by devoncarew** [daftspaniel/Chocolatey-Packages#4]
It looks like there are several dart packages waiting for approval:

    https://chocolatey.org/packages/dart-sdk

Any idea what the hold up is or how to speed up the process? The last approval was from February.

**Comment by DanTup** [comment]
The email sent when the package was submitted said this:

> NOTICE: Currently we have a very large backlog (popularity is a double-edged sword) and are addressing it, but as a result moderation may take upwards of two or more weeks until we resolve issues.

It's only been 6 days since the last version submitted, but the previous ones weren't done in a reasonable timeframe either. Maybe @ferventcoder can advise what the current wait time is like?

@daftspaniel While just checking my emails, I noticed there were some comments made on the original approval when I was maintaining it:

> Would love to see the licenseUrl added.
> In the next release please correct the package title. See our naming rules: https://github.com/chocolatey/choco/wiki/CreatePackages#naming-your-package
> The package title should be “Dart SDK” in this case.

I don't think these would be stopping it from being looked at; but maybe worth addressing; I should've passed them on at the time, sorry :(

**Comment by ferventcoder** [comment]
Thanks for the note on that. We are still getting things in place for the moderation improvements. I took a look and sent you some feedback with a couple of holding issues on getting dartium approved.

**Comment by daftspaniel** [comment]
Thanks @ferventcoder and @DanTup - appreciate the approval coming through :+1: 

I will look at fixing the issues ASAP.
